### ISSUE TITLE
nginx warning 

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#128]
proxy_1       | Certificates found... using HTTPS configuration
proxy_1       | 2023/10/17 12:15:58 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:12
proxy_1       | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:12
proxy_1       | 2023/10/17 12:15:58 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:72
proxy_1       | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:72
proxy_1       | 2023/10/17 12:15:58 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:103
proxy_1       | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:103

I tried to edit the proxy/https.conf.templete file but it seems the error is still there...

**Comment by iiacoban42** [comment]
Closed by #131
