### ISSUE TITLE
Access stored transmission frames from the website

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#18]
- Add a new button to the homepage than leads to a new page where the Uplink and Downlink tables can be queried and the results are displayed. Use and API call for this, in `ewilgs/urls.py` and `ewilgs/views.py`.
- To get started display all contents of the two tables. [Here](https://stackoverflow.com/questions/47492516/how-to-render-django-query-set-as-column-wise-into-html-table) are a few approaches on how to do this. 
- I think it would be nice to convert the query result to a pandas DataFrame, then convert to an HTML table `.to_html()`, then add it to the Django template HTML, but feel to try something different.

**Comment by iiacoban42** [comment]
Might be wise to limit the results to something between 100-1000, or implement an infinite scroll feature, that fetches more data as we scroll through the results.

**Comment by iiacoban42** [comment]
Alright, we'll stick to local time then. I'll add a new issue for sorting with default being most recent on top. I think fetching 250 rows then fetch the next 250 by using a `more` button sounds like a good start for this issue.

Regarding the old data, should that go into separate archive table for each mission or use the new ones? Based on this we might need to adjust the schema. And for DelfiN3xt there's the data displayed as string as opposed to binary, which we can convert to binary to make it consistent with the rest of the system, or leave it as it is.

**Comment by StefanoSperetta** [comment]
I would prefer to find a reasonably practical solution for active satellites and merge all the archive data into the same database (I still hope/expect Delfi-N3xt to wake up one day). Don't worry about the cost of merging the data, I am happy to take care of that, also including converting weird binary strings into more reasonable binary arrays.

My specific plan would be to wait for you to have issue #22 ready and then hack a custom-made script querying the old databases and injecting data. This can serve as an early test to see how things go. I can probably generate quite some stress on the system: I did some earlier tests and the old GS server could query/process something like 10-30 frames per second (the query to assemble the binary data from the processed data is quite complicated, spanning over 5-6 tables without a common index). 

One of the problems that will probably pop-up at that point will be the database: I am not sure how SQLite will deal with an insert process and eventually the webpages querying the data sort-of concurrently so it might require the database to be installed as well.

**Comment by iiacoban42** [comment]
Yep, we'll set up a real database on the actual server, SQLite is not an option.

**Comment by iiacoban42** [comment]
Closed by #26
