### ISSUE TITLE
Implement a Channel for communicating with EWI ground station server

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#20]
Implement a web socked that is only used for to talk to the EWI ground station, [Channels](https://channels.readthedocs.io/en/stable/tutorial/index.html) sounds like a good option.

- This channel should be not accessible to any other parties. It will be used to store transmission data into the database.

**Comment by StefanoSperetta** [comment]
This could be an example of using Channels with a python client (instead of a JS client), maybe it can help you: https://github.com/DelfiSpace/VESSL-Server/tree/Channels-WS-Example

**Comment by iiacoban42** [comment]
Thank you! :)

**Comment by NotUnlikeTheWaves** [comment]
The example you linked Stefano looks useful in setting up a websocket in python.

I'd like to implement this issue but I need a bit more information. Do we have a specification or a (demo) server to program against? How can we test it, and can we automate those tests?

**Comment by StefanoSperetta** [comment]
Right now it is difficult for me to answer, in the sense that the whole concept on my side was never really rigidly defined. The original idea was to have a API similar to the POST API to submit telemetry but that would also allow for a push mechanism (with the push being probably only used initially to send messages to be sent by the ground station but being expended later, eventually). The reason for pushing messages to send to the ground station would be migrating the commanding software to a Django app as well (this is an idea that came out after seeing Django being implemented). It might be simpler to have "dedicated" command applications being embedded in the satellite apps and only accessible to users with the right permissions. This way we would be able to manage operations from a single console.

That said, I think the easiest would be to focus on the transfer infrastructure first: simply create a websocket to interface to a ground station (so fitting in the ewigs app) that can communicate using JSON bidirectionally with multiple clients at the same time. This probably means that, on the server-side, a new thread is spawned per every client (and it includes some keep-alive mechanism to be handled either on the client or on the server side) and this thread can send/receive JSON (with an unspecified content, just pick one that makes your life easy and then we will refine it in the next PR). 

My preference for the client would be python as I could then use this as part of the "data forwarding" infrastructure at the ground station. I wrote a similar client in js (for a webpage) and you can find it here: https://github.com/DelfiSpace/PQ9EGSE/blob/master/src/main/resources/webroot/js/jsonrpc.js

The actual code using my JSON JS client can be found here: https://github.com/DelfiSpace/PQ9EGSE/blob/master/src/main/resources/webroot/js/layoutmanager.js This shows you how all the handlers were used. This client transfers a very stupid JSON structure defined as two strings one named **command** and one named **data** (with the data string often being made by another piece oj JSON). This is purely an example, feel free to change it.

To answer your question on automation, maybe a simple python file connecting to the server and answering a server-initiated ping in JSON would be good enough.

**Comment by NotUnlikeTheWaves** [comment]
Thanks for your extensive reply Stefano :+1:. If I understand the functional requirement correctly we would like the EWI GS to submit telemetry to our application (as opposed to us polling it). Next, we would like to send commands from our application to the EWI ground station. I assume we would get a reply back from that that might contain useful information that might be stored in the database. Please correct me if I'm missing something in this.

Both these actions seem like they can be implemented with APIs on both servers and that they can work independently of each other. I suppose what I'm asking is: what's the reason for using a websocket here? Could you give a functional example so that I can understand the problem better?

**Comment by StefanoSperetta** [comment]
Yes, I think in case the web application (Django) sends a command, we would expect a response from the ground station. An example of this could be "sending a command to the satellite", where the ground station would respond with "message sent" to store in the db. The "message sent" can be sent via the POST API but the "send message" would have to be implemented via polling, which is not a great idea. The POST interface is mostly needed to interface with radio amateur applications (like gr-satellites) that only support GET/POST requests (and not websockets) but the websocket would make commanding much faster. Websockets also would open the possibility of controlling a much more complex application (so not only sending data, but eventually many more functionalities).

As a practical case, I would bring the whole commanding GUI to Django such that everything can be done via the web interface and there, the websocket connection would be the simplest. The use of a websocket (wrt a standard network socket) simplifies the while IT infrastructure as only port 80/443 would need to be opened on the university firewall (and opening anything else than those ports is really a pain in terms of bureaucracy).
