### ISSUE TITLE
Password hashers and salting passwords

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#34]
I'll update this right after I study how hashers and salting work in Django. For now this issue it a todo for me.

**Comment by iiacoban42** [comment]
According to https://docs.djangoproject.com/en/4.0/topics/auth/passwords/, django uses PBKDF2 algorithm with a SHA256 hash which is considered secure. We can of course change it to something else, but if it's not we can close this issue.

**Comment by StefanoSperetta** [comment]
Passwords look nicely encoded. I also tried using the same password on two test users and they appear different in the database so I think we can close this one.
