### ISSUE TITLE
Create DB tables in deploy

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#36]
I am failing to create the Delfi-N3xt table in the deployment version. I am not sure this is the correct procedure to set-up the tables in the production environment.

- I am running the current master (659e63e7cc12cbb26caaf7ce2e2a0c1e9e527aed) 
- I edited the docker-compose-deploy.yml adding (just to have a quick view into the database):
```
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - "5050:80"
        depends_on:
          - "db"
```
- I run the deployment script (`docker-compose -f docker-compose.yml -f docker-compose-deploy.yml up --build`)
- I run a bash console into the container (`docker exec -it delfitlm_app_1 bash`)
- inside the container I run the migrations generation (`python manage.py makemigrations`)

But then I get this error:
```
user@b0ddc44b8421:/app$ python manage.py makemigrations
Migrations for 'delfin3xt':
  delfin3xt/migrations/0001_initial.py
    - Create model Delfin3xt_L0_telemetry
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 190, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 228, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/app/delfin3xt/migrations/0001_initial.py'
```

Running the migration (`python manage.py migrate`) does also generate error because of the previous error:
```
user@b0ddc44b8421:/app$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'delfin3xt' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

I noticed you automatically run the migrations only in the development environment and not on the deployment one  (https://github.com/iiacoban42/DelfiTLM/blob/659e63e7cc12cbb26caaf7ce2e2a0c1e9e527aed/docker-compose.override.yml#L8-L11). I am not sure though what would happen if I rebuild the app with the database having already been built (and eventually containing data) but we can figure this out later.

**Comment by iiacoban42** [comment]
I might have an idea. Try running `python src/manage.py makemigrations` before starting the container, then `python manage.py migrate` while the container is running. I think that should fix it.

**Comment by iiacoban42** [comment]
![image](https://user-images.githubusercontent.com/43474282/144332354-462244bc-76bd-4262-9880-7060ec0c2a6f.png)

Worked on my machine running a flavor of ubuntu.

**Comment by StefanoSperetta** [comment]
I see, the development setup and the deployment setup share the same file system. So migrations have to be executed "on the development environment" as Django has not been started there yet (while it starts automatically in the entrypoint script, as you say).

I think something similar will happen to the admin user creation commands (as they would be run after the server has been started) so setting up the deployment environment requires the development environment as well (basically all python packages have to be installed both on the main machine and on the docker file.

**Comment by iiacoban42** [comment]
I tried creating a superuser in production using the container bash and it worked, seems to be very similar to registering any other user. As far as I understand `makemigrations` has to run while the server is offline, the only thing it's doing is that it compares the db tables from the `models.py` files against the tables from the actual db and creates a script to apply the changes made in `models.py` to the db. You can find them in the migration folders. Then with `migrate` the changes compiled by `makemigrations` are executed as a db transaction, so the db needs to be up. `makemigrations` would be necessary only if the models are changed or created for the first time, which will only happen in development that's probably why the command fails in production.

**Comment by StefanoSperetta** [comment]
Actually the issue is related to the fact that `makemigrations` has to generate the migrations file (_0001_initial.py_) and store it in the container (which is read-only): https://github.com/cookiecutter/cookiecutter-django/issues/2360

I added the `makemigrations` command to the Dockerfile:

```
WORKDIR /app
COPY ./scripts /scripts

RUN python manage.py makemigrations

# add executable permission to the scripts folder
# scripts will run a uwsgi service that will host the app
RUN chmod +x /scripts/*
```

which makes sure the migrations file is in the container, then all other commands can be issues after the container was started:
 -  `docker exec -it  delfitlm_app_1 /bin/bash`
 -  `python manage.py migrate`
 
I guess we probably should instead simply add the _0001_initial.py_ file to the repository (instead of generating it in production) instead of generating it in the Dockerfile: https://stackoverflow.com/questions/28035119/should-i-be-adding-the-django-migration-files-in-the-gitignore-file

**Comment by iiacoban42** [comment]
Yes, adding these files in development sounds like a better idea. Actually running `makemigrations` beforehand ensures that the definition of the models and the relationships are correct, otherwise it throws a bunch of errors or warnings.
