### ISSUE TITLE
Make the website more usable 

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#39]
Make the login forms more usable, add menus/button, for registering, login, logout etc. You can be creative here. Don't spend too much time on this. It should be functional not pretty at this stage, but also more organized than our current setup.

**Comment by NotUnlikeTheWaves** [comment]
Nice, I think this would be a great visual improvement. How do you feel about using a solution that takes care of styling and perhaps some components for us, for example bootstrap or tailwind? To myself this would be faster than writing and maintaining CSS on top of the HTML, not to think of the browser compatibilities :smile:. If this is something shared in our team then maybe this would be a good opportunity to explore it?

**Comment by iiacoban42** [comment]
Yes indeed that's the way to go. With this issue I would go for something very minimalistic, as in just the HTML elements in a readable form with as little CSS as possible (close to nothing) just to get the functionality there. We can do fancy visuals later as it's not a priority.
