### ISSUE TITLE
Add API call that add data to the Downlink table

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#40]
Add an API call that receives data as a JSON and inserts it into the Downlink table. This issue together with #20 should make up the downlink pipeline.

**Comment by NotUnlikeTheWaves** [comment]
I think this could use a little bit more information, do we have an idea on how the data is provided to us? Is there a way to get test data to test this feature with?

**Comment by StefanoSperetta** [comment]
This is just an example (so feel free to play with it) coming from the Delfi-N3xt client: it is written in Java but I think the JSON code should be pretty understandable. 

```
public String submit(Date rxTime, String frame, double frequency, double qos) throws IOException, ParseException
{        
        // Open a connection(?) on the URL(??) and cast the response(???)
        HttpURLConnection connection = (HttpURLConnection) urlSubmit.openConnection();
        connection.setRequestMethod("POST"); 
        connection.setRequestProperty("User-Agent", "Java client");
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setDoOutput(true); 
        
        // create the object to submit
        JSONObject obj = new JSONObject();

        int time_send = (int)((new Date()).getTime() / 1000L);
        int time_rec = (int)(rxTime.getTime() / 1000L);

        obj.put("user", user);
        obj.put("pass", pass);
        obj.put("receptionTime", time_rec);
        obj.put("frequency", frequency);
        obj.put("qos", qos);
        obj.put("frame", frame);

        // send the data structure
        try (DataOutputStream wr = new DataOutputStream(connection.getOutputStream())) 
        {
            wr.writeBytes(obj.toString());
        }

        .....
```

I am specifically using the User-Agent field to identify which client is submitting the frame (to fill the client in the data table) and in this specific case I am using a username and a password. Maybe a smarter solution can be used (something like a passphrase of a token such that we do not store the password in plain text). We might even think about using the authentication header for the passphrase....

One point here is that I only use a "frame" (as in downlink frame). We might make a specific distinction rxFrame and txFrame to make sure we only have one API for both.

It should be possible to have both a webpage (handling POST requests) and a websocket (like https://github.com/DelfiSpace/VESSL-Server/blob/Channels-WS-Example/Server/vessl_server/asgi.py): maybe this could simplify the work...
