### ISSUE TITLE
Classify telemetry frames by satellite 

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#46]
Unprocessed downlink frames should be classified by satellite and copied to their respective mission table and set the processed flag from the `Downlink` table to `True`. Write the code for this issue in the `ewilgs` app.

**Comment by iiacoban42** [comment]
@StefanoSperetta can we do this solely based on frequency? We could also start of by identifying only PQ frames if you consider this feature valuable for the launch.

**Comment by StefanoSperetta** [comment]
I think the best way would be to filter per "header": all telemetry has to start with a certain header somehow (like AX.25) so all frames, in the end, begin with a certain fixed sequence (or maybe a set of different sequences with this set being just a few possibilities).

For example:
 - 0x8ea49eaa9c88e088988c92a0a26103f0 for Delfi-PQ 
 - 0xa8989a4040400088988c9286660103f0 for Delfi-C3

As a start, I would simply hardcode "If telemetry starts with %s" then associate with satellite. If there is no satellite for that specific starting sequence then ignore it (and we might also delete it eventually later on).

**Comment by iiacoban42** [comment]
Closed by #89
