### ISSUE TITLE
Handle CSRF verification failure

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#48]
If a user is logged in in the members/profile page and inactive for a while (no idea exactly how long, in my case was ~1h), then the user clicks any link, a CSRF validation error is triggered (which is great!) but the error should be handled and redirect to the login page instead of throwing a 403 error:

![image](https://user-images.githubusercontent.com/19912937/148388929-715abb2f-221e-468c-bf90-1a16070b54b2.png)

**Comment by StefanoSperetta** [comment]
The same happens if I am logged in on the members profile page and I restart the server... the session is preserved. Is this one an intended behavior? It is handy for the user (as a server restart would not be noticed) but I am not sure it is a risk for security.

The former problem should definitely be addressed but I am not sure this one *is* actually a problem.

**Comment by iiacoban42** [comment]
I don't see a security risk for keeping the session after a server restart, I imagine this is done in practice quite often especially for distributed systems. We could add an auto logout after 30min-1h of idle time to strengthen security https://pythonrepo.com/repo/bugov-django-auto-logout-python-django-utilities.

**Comment by StefanoSperetta** [comment]
The issue seems not to be present anymore.
