### ISSUE TITLE
Naive datetime

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#66]
The Django unit test reports these errors:
```
../opt/hostedtoolcache/Python/3.[9](https://github.com/iiacoban42/DelfiTLM/runs/5069197140?check_suite_focus=true#step:5:9).[10](https://github.com/iiacoban42/DelfiTLM/runs/5069197140?check_suite_focus=true#step:5:10)/x64/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Downlink.frame_time received a naive datetime (2021-[12](https://github.com/iiacoban42/DelfiTLM/runs/5069197140?check_suite_focus=true#step:5:12)-19 02:20:[14](https://github.com/iiacoban42/DelfiTLM/runs/5069197140?check_suite_focus=true#step:5:14).959630) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Downlink.send_time received a naive datetime (2021-12-19 02:20:14.959630) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Downlink.receive_time received a naive datetime (2021-12-19 02:20:14.959630) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
```

These errors refer to the code here https://github.com/iiacoban42/DelfiTLM/blob/bd1b93dd3a283dcba3128e6d8a94dbd1e1132ee1/src/ewilgs/save_frames.py#L38-L54 about the handling of the datetime objects in the save_frame function on the ewigs application.

It is important to add more unit tests for this function to ensure the time submitted is the same (and with the same time zone) as the time stored. Please see Issue #65 for more details on the submission fields to make sure they are consistent.

**Comment by iiacoban42** [comment]
The warning is triggered because there is no timezone specified with the submitted timestamps. I can think of two approaches to fix this:
- we ask for UTC timestamps, then convert to NL timezone
- ask for timezone (extra field in the JSON), then convert to NL timezone
