### ISSUE TITLE
Logging operator in uplink

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#70]
When storing downlink frames in the database, the "receiving ground station user" (radio_amateur) is used per each received frame. When it comes to the uplink frame, the frame is reported by the gound station and it would be stored in the database using the ground station "user". It would be important to actually store the operator's username as it is the person that decided to command the satellite.

For the time being, this is a secondary issue, but it is important to record who submits the command (and eventually via which ground station) rather than the ground station that send the command only (this is mostly for traceability).

I currently have no real preference for how to do this as, also, the current system does not have any interface for an operator to send a command to the system but simply log the command that the ground station sent.

**Comment by iiacoban42** [comment]
The Uplink table has a foreign key field that stores the username of the operator for each frame. It's called radio_amateur, perhaps we should change it to operator. So the schema seems to be in order, we just need to tweak the submission part on the server.

**Comment by iiacoban42** [comment]
This one is implemented so I'm going to close it.
