### ISSUE TITLE
Hardcoded hostname in deployment configuration without SSL

### ISSUE THREAD

**Issue by StefanoSperetta** [iiacoban42/DelfiTLM#72]
The hostname is hardcoded in [http.conf](https://github.com/iiacoban42/DelfiTLM/blob/5407b8ee8db772d9634edc0ee6b088e2834789b9/proxy/http.conf#L15) in the proxy folder so deployment cannot be tested on other machines.

**Comment by iiacoban42** [comment]
Closed by #73
