### ISSUE TITLE
Add bootstrap to the front-end 

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#75]
Let's make the website a bit more modern with bootstrap. 

- Make the forms and homepage pretty 
- Play around with the table view for telemetry frames, see what bootstrap has to offer  

If anyone has other ideas or suggestions for the front end, please comment.

**Comment by StefanoSperetta** [comment]
Nice idea, I am listing here some extra information / webpages / ideas I am thinking about having:
- a homepage presenting the website, how to contact us, etc..
- one page presenting each satellite (with eventually more than one page) telling general info about the satellite and how to receive the satellites and submit telemetry
- eventually, a page showing where the different satellites are (based on the TLE, I was thinking about [this](https://leafletjs.com/examples/mobile/)) and potentially calculating passes
- Reception statistics (per satellite) to show which radio amateur has received more messages (similar to the top right widget in [here](https://dashboard.satnogs.org/d/O-wbcw1nk/delfi-pq?orgId=1))
- a satellite dashboard (implemented with grafana, we can just display dashboards as iframes), similar to [this](https://dashboard.satnogs.org/d/O-wbcw1nk/delfi-pq?orgId=1) (publicly visible) and a private version (for operators)
- a page to generate commands to the satellites (per satellite) only accessible to operators

I am not sure if it would be easier to have the text in the database (using Django as content management system) or as static pages though.

**Comment by iiacoban42** [comment]
Nice, I like it! The end website is gonna look amazing! I think static pages should do the job. We could use django templates, as we'll probably have very similar, if not the same page structure for all satellites. Then we'll parameterize html elements and fill-in sat specific content.
